version: '3.7'
services:

  db:
    image: postgres:12-alpine
    container_name: it_ext_db
    restart: always
    env_file: .env
    ports:
      - 5433:5433
    volumes:
      - psql_data:/var/lib/postgresql/data
      - psql_data:/docker-entrypoint-initdb.d

volumes:
  psql_data:
    name: it_ext_db_data
    driver: local
